version: '3.5'

services:

  furcifer_efficientnet_b0:
    image: furcifer_efficientnet_b0:latest
    hostname: furcifer_efficientnet_b0
    expose:
      - "8001"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  furcifer_split_mobilenet_v3_split5_head:
    image: furcifer_split_mobilenet_v3_split5_head:jetson5.0.2
    hostname: furcifer_split_mobilenet_v3_split5_head
    expose:
      - "8050"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - furcifer_efficientnet_b0
    ports:
      - "8000:80"

networks:
  default:
    driver: bridge
    name: furcifer

  # app2:
  #   image: your-app-image:tag
  #   networks:
  #     - app-network

# networks:
#   app-network: