version: '3.5'

services:

  furcifer_efficientnet_b0:
    image: furcifer_efficientnet_b0:latest
    hostname: furcifer_efficientnet_b0
    expose:
      - "8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - furcifer_efficientnet_b0
    ports:
      - "8000:80"

networks:
  default:
    driver: bridge
    name: furcifer

  # app2:
  #   image: your-app-image:tag
  #   networks:
  #     - app-network

# networks:
#   app-network: